export interface Directives {
  signature: string
  date: string
  agreeThatTheirSignatureIsValid: boolean
  healthCarePowerOfAttorney: boolean
  healthCarePowerOfAttorneyName: string
  phoneNumber: string
  preHospitalMedicalDirectives: boolean
  doYouHaveALivingWill: boolean
}

export interface Hippa {
  hippaSignature: string
  signatureDate: string
  signatureCheckBoxConsent: boolean
  name: string
  relationShip: string
  name2: string
  relationShip2: string
  name3: string
  relationShip3: string
  name4: string
  relationShip4: string
}

export interface PacketInfo {
  firstName: string
  lastName: string
  preferredName: string
  BirthDateValue: string
  phoneNumberValue: string
  homePhone: string
  emailValue: string
  addressValue: string
  addressValue2: string
  cityValue: string
  USStateValue: string
  zipCodeValue: string
  socialValue: string
  isCheckedMale: boolean
  isCheckedFemale: boolean
  isCheckedOther: boolean
  single: boolean
  married: boolean
  divorced: boolean
  widowed: boolean
  separated: boolean
  withPartner: boolean
  MayWeTakeYourPicture: string
  Ethnicity: string
  HowDidTheyHearAboutUs: string
  pictureOfFrontOfDriverLicense: string
  pictureOfTheirFace: string
  nameOfEmergencyContact: string
  EmergencyContactRelationShip: string
  EmergencyContactPhoneNumber: string
  howDoTheyWishToPay: string
  primaryInsurance: string
  primaryInsuranceID: string
  primaryInsuranceGroup: string
  primaryInsurancePhone: string
  primaryInsuranceAddress1: string
  primaryInsuranceAddress2: string
  primaryInsuranceCity: string
  primaryInsuranceState: string
  primaryInsuranceZipCode: string
  primarySubscribersName: string
  primarySubscribersDOB: string
  secondaryInsurance: string
  secondaryInsuranceID: string
  secondaryInsuranceGroup: string
  secondaryInsurancePhone: string
  secondaryInsuranceAddress1: string
  secondaryInsuranceAddress2: string
  secondaryInsuranceCity: string
  secondaryInsuranceState: string
  secondaryInsuranceZipCode: string
  secondarySubscribersName: string
  secondarySubscribersDOB: string
  primaryPictureOfInsuranceCardFront: string
  primaryPictureOfInsuranceCardBack: string
  secondaryPictureOfInsuranceCardFront: string
  secondaryPictureOfInsuranceCardBack: string
  retailPharmacyName: string
  retailPharmacyCrossStreet1: string
  retailPharmacyCrossStreet2: string
  retailPharmacyPhoneNumber: string
  retailPharmacyFaxNumber: string
  mailOrderPharmacyName: string
  mailOrderPharmacyAddress1: string
  mailOrderPharmacyAddress2: string
  mailOrderPharmacyPhoneNumber: string
  areYouAllergicToLatex: string
  areYouAllergicToSelfish: string
  areYouAllergicToIodine: string
  PatientDrugAllergies: string
  dateOfLastPAP: string
  wasPapNormalOrAbnormal: string
  dateOfLastMammogram: string
  wasMammogramNormalOrAbnormal: string
  dateOfLastPSA: string
  wasPSANormalOrAbnormal: string
  allMajorIllnesses: string
  allMajorSurgeriesAndHospitalizations: string
  allMedicalHistoryOfDisease: string
  listOfAllCurrentMedications: string
  boneDensityScreening: string
  BoneDensityScreeningDate: string
  wasBoneDensityScreeningNormalOrAbnormal: string
  colonoscopyScreening: string
  colonoscopy: string
  dateOfLastColonoscopyScreening: string
  wasColonoscopyScreeningNormalOrAbnormal: string
  haveTheyEverSmoked: string
  howManyPacksPerDay: string
  anyOtherTobaccoOrEcigarettes: string
  describeOtherTobaccoUse: string
  doYouDrinkCoffee: string
  howManyCupsPerDay: string
  doYouDrinkAlcohol: string
  howManyDrinksPerWeek: string
  doYoCurrentlyUseRecreationalDrugs: string
  describeRecreationalDrugUse: string
  doYouUseIllegaLStreetDrugs: string
  describeIllegalStreetDrugUse: string
  doYouFeelDepressed: string
  doYouCryFrequently: string
  doYouHaveLittleInterestInDoingThings: string
  doYouFeelHopelessDownOrDepressed: string
  doYouHaveTroubleFallingAsleepOrSleepingTooMuch: string
  doYouFeelTiredOrHaveLittleEnergy: string
  doYouHavAPoorAppetiteOrOverEating: string
  doYouFeelBadAboutYourself: string
  troubleConcentrating: string
  doYouMoveOrSpeakSlowly: string
  thoughtsYouWouldBeBetterOffDead: string
  isStressAMajorProblem: string
  doYouPanicWhenStressed: string
  haveYouEverAttemptedSuicide: string
  familyMedicalAlcoholismAddiction: string
  familyMedicalBleedingDisorders: string
  familyMedicalCancer: string
  familyMedicalDiabetes: string
  familyMedicalHeartAttack: string
  familyMedicalHighBloodPressure: string
  familyMedicalHighCholesterol: string
  familyMedicalKidneyDisease: string
  familyMedicalMentalIllness: string
  familyMedicalStroke: string
  familyMedicalTuberculosis: string
  isYourFatherStillLiving: string
  isYourMotherStillLiving: string
  patientMedicalReviewSignature: string
  patientMedicalReviewSignatureDate: string
  PatientMedicalReviewSignatureCheckBox: string
  hippa: Hippa
  AdvancedDirectives: Directives
  financialPolicySignature: string
  financialPolicySignatureDate: string
  financialPolicySignatureCheckBox: boolean
}
