export interface WeightLossSurveyTypes {
  emailValue: string
  patientsName: string

  whyLossWeight: string
  weightGoals: string
  timeFrame: string

  mostWeighedAsAdult: string
  ageAtAdultWeight: string
  leastWeighedAsAdult: string
  ageAtAdultLeastWeight: string
  weightChangeDuringLife: Array<string>
  weightGainedInPast: Array<string>

  challengesOfWeightManagement: string
  hopesForWeightLossManagement: string
  commitmentsToWeightLoss: string

  onYourOwn: string
  checkIfTried: Array<string>
  onYourOwnStartDate: string
  onYourOwnEndDate: string
  onYourOwnWeightLoss: string
  onYourOwnReasonForStopping: string
  onYourOwnReasonForRegain: string
  atkinsOrLowCarbohydrate: string
  atkinsOrLowCarbohydrateStartDate: string
  atkinsOrLowCarbohydrateEndDate: string
  atkinsOrLowCarbohydrateWeightLoss: string
  atkinsOrLowCarbohydrateReasonForStopping: string
  atkinsOrLowCarbohydrateReasonForRegain: string
  jennyCraig: string
  jennyCraigStartDate: string
  jennyCraigEndDate: string
  jennyCraigWeightLoss: string
  jennyCraigReasonForStopping: string
  jennyCraigReasonForRegain: string
  nutrisystem: string
  nutrisystemStartDate: string
  nutrisystemEndDate: string
  nutrisystemWeightLoss: string
  nutrisystemReasonForStopping: string
  nutrisystemReasonForRegain: string
  weightWatchers: string
  weightWatchersStartDate: string
  weightWatchersEndDate: string
  weightWatchersWeightLoss: string
  weightWatchersReasonForStopping: string
  weightWatchersReasonForRegain: string
  slimfast: string
  slimfastStartDate: string
  slimfastEndDate: string
  slimfastWeightLoss: string
  slimfastReasonForStopping: string
  slimfastReasonForRegain: string
  optifast: string
  optifastStartDate: string
  optifastEndDate: string
  optifastWeightLoss: string
  optifastReasonForStopping: string
  optifastReasonForRegain: string
  otherLiquidDiet: string
  otherLiquidDietStartDate: string
  otherLiquidDietEndDate: string
  otherLiquidDietWeightLoss: string
  otherLiquidDietReasonForStopping: string
  otherLiquidDietReasonForRegain: string
  other: string
  otherName: string
  otherStartDate: string
  otherEndDate: string
  otherWeightLoss: string
  otherReasonForStopping: string
  otherReasonForRegain: string

  adipex: string
  adipexStartDate: string
  adipexEndDate: string
  adipexWeightLoss: string
  adipexReasonForStopping: string
  adipexReasonForRegain: string
  alli: string
  alliStartDate: string
  alliEndDate: string
  alliWeightLoss: string
  alliReasonForStopping: string
  alliReasonForRegain: string
  belviq: string
  belviqStartDate: string
  belviqEndDate: string
  belviqWeightLoss: string
  belviqReasonForStopping: string
  belviqReasonForRegain: string
  dexatrim: string
  dexatrimStartDate: string
  dexatrimEndDate: string
  dexatrimWeightLoss: string
  dexatrimReasonForStopping: string
  dexatrimReasonForRegain: string
  herbalWeightLoss: string
  herbalWeightLossStartDate: string
  herbalWeightLossEndDate: string
  herbalWeightLossWeightLoss: string
  herbalWeightLossReasonForStopping: string
  herbalWeightLossReasonForRegain: string
  meridia: string
  meridiaStartDate: string
  meridiaEndDate: string
  meridiaWeightLoss: string
  meridiaReasonForStopping: string
  meridiaReasonForRegain: string
  phenfen: string
  phenfenStartDate: string
  phenfenEndDate: string
  phenfenWeightLoss: string
  phenfenReasonForStopping: string
  phenfenReasonForRegain: string
  qsymia: string
  qsymiaStartDate: string
  qsymiaEndDate: string
  qsymiaWeightLoss: string
  qsymiaReasonForStopping: string
  qsymiaReasonForRegain: string
  redux: string
  reduxStartDate: string
  reduxEndDate: string
  reduxWeightLoss: string
  reduxReasonForStopping: string
  reduxReasonForRegain: string
  otherSuppliments: string
  otherSupplimentsName: string
  otherSupplimentsStartDate: string
  otherSupplimentsEndDate: string
  otherSupplimentsWeightLoss: string
  otherSupplimentsReasonForStopping: string
  otherSupplimentsReasonForRegain: string

  childrenUnderEighteen: string
  childrenUnderEighteenCheckBox: string
  familyMembersObese: string
  support: string
  supportExplination: string

  eatingDisorder: string
  anorexiaNervosa: string
  bingeEating: string
  bulimia: string
  eatingTooMuch: string
  sleepHours: string
  restedWhenWakeUp: string
  doYouSnore: string
  wearEquipment: string
  howManyNights: string
  sleepWellness: string
  sittingAndReading: string
  watchingTv: string
  sittingInPublic: string
  carPassanger: string
  lyingDown: string
  talkingToSomeone: string
  sittingQuietlyAfterLunch: string
  inCarWhileStopped: string
  total: string
  typicalDay: string

  enjoyExercise: string
  gymMembership: string
  exerciseEquipment: string
  exerciseRegularly: string
  badExperienceExercise: string
  sixAm: string
  nineAm: string
  twelvePm: string
  threePm: string
  sixPm: string
  ninePm: string
  exerciseWeekly: string
  describeExercise: string
  difficultyGettingUpFromFloor: string
  typeOfExercise: string
  exercisePreference: string
  athleteInSchool: string
  confidentIncrease: string
  majorBenefitsOfExercise: string
  exerciseBarriers: string
  minutesPerDay: string
  daysPerWeek: string

  confidenceWeightLossDiet: string
  majorBarriersDiet: string
  favoriteFoods: string
  breakfastTypeOfFood: string
  breakfastProteinOrCarbs: string
  breakfastCalories: string
  lunchTypeOfFood: string
  lunchProteinOrCarbs: string
  lunchCalories: string
  dinnerTypeOfFood: string
  dinnerProteinOrCarbs: string
  dinnerCalories: string
  snackOneTypeOfFood: string
  snackOneProteinOrCarbs: string
  snackOneCalories: string
  snackTwoTypeOfFood: string
  snackTwoProteinOrCarbs: string
  snackTwoCalories: string
  coffeeTypeOfFood: string
  coffeeProteinOrCarbs: string
  coffeeCalories: string
  sodaTypeOfFood: string
  sodaProteinOrCarbs: string
  sodaCalories: string
  candyOrSweetsTypeOfFood: string
  candyOrSweetsProteinOrCarbs: string
  candyOrSweetsCalories: string
  otherTypeOfFood: string
  otherProteinOrCarbs: string
  otherCalories: string
  numPeopleLiveWith: string
  eatTogether: string
  whoDoesShopping: string
  whoDoesCooking: string
  foodIntolerance: string
  foodIntoleranceList: string
  stressEating: string
  stressEatingDetails: Array<string>
  bingeEatingExperience: string
  bingeEatingDetails: Array<string>
  snackingExperience: string
  snackingDetails: Array<string>
  eatingMiddleOfNightExperience: string
  eatingMiddleOfNightDetails: Array<string>
  skippingMealsExperience: string
  skippingMealsDetails: Array<string>
  eatingOutExperience: string
  eatingOutDetails: Array<string>
  eatingInFrontOfTVExperience: string
  eatingInFrontOfTVDetails: Array<string>
  eatingAtDeskExperience: string
  eatingAtDeskDetails: Array<string>
  portionSizeExperience: string
  portionSizeDetails: Array<string>
  eatingTooFastExperience: string
  eatingTooFastDetails: Array<string>
  notSatifiedExperience: string
  notSatifiedDetails: Array<string>
  regularSoda: string
  regularSodaCount: Array<string>
  juice: string
  juiceCount: Array<string>
  sweetTea: string
  sweetTeaCount: Array<string>
  alchoholBeverage: string
  alchoholBeverageList: Array<string>
  friedFoods: string
  friedFoodsCount: Array<string>
  fruitServings: string
  vegetablesServings: string
  wholeGrainsServings: string
  lowFatDairyServings: string
  leanProteinServings: string
  daysPerWeekExplination: string
  medicalHistory: string
  medicationsTaken: string
  medicationsTakenList: Array<string>
}
